//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roniz.WCF.P2P.Sync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roniz.WCF.P2P.Sync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception at business logic level catch by the infrastructure in order to not fault the channel.
        /// </summary>
        internal static string ExceptionCatchFromBusinessLogic {
            get {
                return ResourceManager.GetString("ExceptionCatchFromBusinessLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call open when State is Opening or already Opened.
        /// </summary>
        internal static string OpenErrorOpeningOpened {
            get {
                return ResourceManager.GetString("OpenErrorOpeningOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call operation while communication state is not opened or online.
        /// </summary>
        internal static string OperationNotAllowedNotOpenedOrOnlineComunicationState {
            get {
                return ResourceManager.GetString("OperationNotAllowedNotOpenedOrOnlineComunicationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communicationState contain state that cannot converted.
        /// </summary>
        internal static string SynchronizationCommunicationStateHelper_Convert_communicationState_contain_state_that_cannot_converted {
            get {
                return ResourceManager.GetString("SynchronizationCommunicationStateHelper_Convert_communicationState_contain_state_" +
                        "that_cannot_converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when using SynchronizationMode.Reliable the given re-sync interval must be &gt; 0.
        /// </summary>
        internal static string SynchronizationModeReliableReSyncIntervalBiggerThenZero {
            get {
                return ResourceManager.GetString("SynchronizationModeReliableReSyncIntervalBiggerThenZero", resourceCulture);
            }
        }
    }
}
